### ISSUE TITLE
BAM files size limitation

### ISSUE THREAD

**Issue by binfyun** [igvteam/igv-reports#23] opened 2019-03-12 19:50 UTC
Hi,
It seems that there is a limitation on how many reads you can load in the html output?
A couple tries, looks like:
1. Cannot display the tumor and its matched normal reads(beneath the tumor read window) at the same time? 
2. Not all mutations' reads are displayed in the read window

Thanks

**Comment by jrobinso** [comment] 2019-03-12 22:24
There's no limit that I'm aware of,  and I don't understand your points 1 and 2.   You can load as many tracks as you like (e.g. 1 for tumor and 1 for normal).

Please provide more details, and ideally a test case to reproduce problems you are having.  Or at the minimum screenshots.

**Comment by binfyun** [comment] 2019-03-20 00:38
Hi @jrobinso, thank you for the reply

So this is what I ran:
"create_report 35439742-T_Matched_annovar.vcf_processed.vcf.gz Homo_sapiens_assembly19.fasta --ideogram cytoBand.txt --flanking 1000 --infoColumns GENE,COSMIC_ID --tracks 35439742-T_Matched_annovar.vcf_processed.vcf.gz,35439742-T_bc276_IMPACTv6-CLIN-20190168_L000_mrg_cl_aln_srt_MD_IR_BR.bam"

dummy vcf file attached:
[Matched_annovar.vcf_processed_subset.txt](https://github.com/igvteam/igv-reports/files/2986040/Matched_annovar.vcf_processed_subset.txt)

The BAM was processed (post BQSR and index) size=3.6G <-the limitation I was referring to

igv_viewer.html was generated but without reads in the window: (screenshot attached)
<img width="1897" alt="Screen Shot 2019-03-19 at 8 34 59 PM" src="https://user-images.githubusercontent.com/10803002/54650878-bbe60d80-4a86-11e9-913c-57d0616770b4.png">

Thanks again.

**Comment by jrobinso** [comment] 2019-03-20 03:21
Its impossible for me to help with this without an example case I can run.    

What happens if you load the bam into IGV desktop and go to the locations specified in your VCF?

**Comment by jrobinso** [comment] 2019-03-20 03:42
BTW the bam file I'm testing on is ~300 GB

**Comment by binfyun** [comment] 2019-03-20 04:33
Attached screenshot for KRAS 12:25398281 in IGV:
![Screen Shot 2019-03-20 at 12 28 54 AM](https://user-images.githubusercontent.com/10803002/54659266-7ab22580-4aa7-11e9-92dc-65915f1a2ac7.png)

I had attached a subset of the variants (
[Matched_annovar.vcf_processed_subset.txt](https://github.com/igvteam/igv-reports/files/2986519/Matched_annovar.vcf_processed_subset.txt)
) I used from the above example. Would this be sufficient? 

Thanks.

**Comment by jrobinso** [comment] 2019-03-20 04:39
We're not communicating.   I need a command line I can run,  the VCF is not enough.    If you can create an example you can zip up I will look into it.     Include the command line you used  in the zip, as a .txt or .sh file.   First unzip it yourself and insure that it runs without error.   Is that cleare enough?  You can use samtools to extract a small portion of your bam for this.

**Comment by jrobinso** [comment] 2019-03-20 04:41
BTW,  I see reference to some broad filepaths in your VCF.   I have access to the Broad filesystem if your files are there.

**Comment by binfyun** [comment] 2019-03-20 05:12
If you have everything set up and ready to go, can't you just run the following command from your end? (ignore the ideogram and additional tracks for now, just provide reference genome and BAM file)
create_report "the vcf subset i had attached" "your hg19 reference genome" --flanking 1000 --infoColumns GENE,COSMIC_ID --tracks "your BAM file"

**Comment by jrobinso** [comment] 2019-03-20 06:52
Yes I can, works perfectly.   Did you see the example in the repository?

**Comment by jrobinso** [comment] 2019-03-20 07:04
Are there any errors in your console?

**Comment by jrobinso** [comment] 2019-03-20 07:22
There's something odd here,  I'm not sure what and its getting late.   I'll pick it up tomorrow.

**Comment by jrobinso** [comment] 2019-03-20 07:32
Are you sure your bam sequence names are "1, 2, 3,..." etc and not  "chr1, chr2, chr3..."?    They need to match the vcf and fasta.

**Comment by jrobinso** [comment] 2019-03-20 07:50
The following runs without error and produces a report with alignments at every variant

```
create_report Matched_annovar.vcf_processed_subset.vcf https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/b37/human_g1k_v37.fasta --flanking 1000 --infoColumns GENE,COSMIC_ID --tracks http://1000genomes.s3.amazonaws.com/phase3/data/HG01879/alignment/HG01879.mapped.ILLUMINA.bwa.ACB.low_coverage.20120522.bam
```

BTW in the next release the infoColumns and tracks parameters are changing to be posix compliant, the above would be 

```
create_report Matched_annovar.vcf_processed_subset.vcf https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/b37/human_g1k_v37.fasta --flanking 1000 --info-columns GENE COSMIC_ID --tracks http://1000genomes.s3.amazonaws.com/phase3/data/HG01879/alignment/HG01879.mapped.ILLUMINA.bwa.ACB.low_coverage.20120522.bam

```

**Comment by binfyun** [comment] 2019-03-20 17:04
> Are you sure your bam sequence names are "1, 2, 3,..." etc and not "chr1, chr2, chr3..."? They need to match the vcf sequence names.

Yes they are

**Comment by jrobinso** [comment] 2019-03-20 17:06
So since your command works with the BAM noted above I don't know what to do with this without access to the BAM.

**Comment by jrobinso** [comment] 2019-03-20 17:09
Here's the resulting report.  
[igvjs_viewer.html.zip](https://github.com/igvteam/igv-reports/files/2989299/igvjs_viewer.html.zip)

**Comment by jrobinso** [comment] 2019-03-21 02:26
I'm going to close this since the answer to the original question is no, there is no bam file size limitation.  If you are able to create a test case I can reproduce please open a new issue.

**Closed by jrobinso** 2019-03-21 02:26 UTC
