### ISSUE TITLE
igv-reports doesn't display bam but igv does

### ISSUE THREAD

**Issue by azbard** [igvteam/igv-reports#57] opened 2021-12-14 20:18 UTC
Absolute noob here - be gentle.

Is there any conceptual reason why a bam/bed combo would display fine in igv proper (java) but only the bed shows up in a report generated as follows?

create_report bedfile.bed hg19.fasta --tracks bamfile.bam

These two made with the same files...
![Screenshot 2021-12-14 151244](https://user-images.githubusercontent.com/83711448/146073092-3db651ef-3e95-490b-9f45-3d65073e77c5.png)
![image](https://user-images.githubusercontent.com/83711448/146078814-f6921eb7-b343-42df-9a52-e0e3152dadc9.png)
 
[edited to show matching locations in igv and igv-reports]

**Comment by jrobinso** [comment] 2021-12-14 20:31
In your igv-reports screenshot I see chr20 is displayed, but in the IGV desktop screenshot chr5.   If you are displaying the chr5 data at the chr20 location then you won't see any alignments.  I think this is the root cause, but its difficult to say how this could occur without having the files.   If you're able to share the report (generated html) you can email it privately to igvteam (at) broadinstitute.org and I will have a look.

**Comment by jrobinso** [comment] 2021-12-14 21:23
Thanks for the data.  I think your bed file might be malformed, based on the table column names in your screenshot above.   Could you zip and attach it (just the bedfile).

**Comment by azbard** [comment] 2021-12-15 13:51
I figure out the report not showing the tracks - my pysam library was causing the problem - it had been altered for another project. Ugh - this was all my own fault.

The bed though...
[bedfile-copy.zip](https://github.com/igvteam/igv-reports/files/7719868/bedfile-copy.zip)

**Comment by jrobinso** [comment] 2021-12-15 16:52
OK,  python is like that.    RE the bed file,  "bed" uses zero-based
coordinates, unlike other formats like VCF and GFF.  So your start
coordinate should be 1 less than the end coordinate for 1-base variants.

**Comment by ankit-21** [comment] 2021-12-16 14:38
Thank you for your support and prompt response to our issue. We were able to get igv-reports to function as desired. Really love this tool.
Feel free to close this issue.

**Closed** 2021-12-16 20:33 UTC
